config/routes.rb
Rails.application.routes.draw do
  get 'info/create'

  root 'home#index'

  match 'help', to: 'home#help', via: :get

  match 'signup', to: 'users#new', via: :get

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/sessions',  to: 'sessions#create',         via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   :help %></li>
      <li><%= link_to "Sign up", :signup %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
       <div class="navbar-header">
          <%= link_to "sample app", root_path, id: "logo" %>
       </div>
       <div>
          <ul class="nav navbar-nav pull-right">
             <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <% if signed_in? %>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <li><%= link_to "Sign up", signup_path %></li>
              <% end %>
          </ul>
       </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= FullTitle(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>